version: "3.10"
services:
  test_api:
    build:
      context: .
    container_name: test_api
    env_file:
      - .env_test_db
    depends_on:
      - redis
    command: /bin/bash -c "sleep 15 && pytest -v"

  test_db:
    image: postgres:15.1-alpine
    container_name: test_db
    env_file:
      - .env_test_db

  redis:
    image: redis:7
    container_name: redis
    env_file:
      - .env_test_db
    depends_on:
      - test_db
